
// publish from collection recipes of only authorized user
Meteor.publish('recipes', function(){
    return Recipes.find({author: this.userId});
});

Meteor.publish('singleRecipe', function(id){
    // check awailable from check package
    check(id, String);
    // _id generated automatically, id received from RecipeSingle.helpers (generated by FlowRouter?)
    return Recipes.find({_id: id});
});